# Python para Dados - Atividade de Fixação Numpy  

In [4]:
import numpy as np

Atividades Introdutórias:

1. Crie um array com 4 linhas e 3 colunas com valores aleatórios.  

In [2]:
np.random.random((4,3))

array([[0.71107387, 0.71949797, 0.91233158],
       [0.6347197 , 0.31314613, 0.05393124],
       [0.1179061 , 0.76161776, 0.59187087],
       [0.8178129 , 0.84225675, 0.85521913]])

2. Crie um array com valores inteiros, 3 linhas e 5 colunas com valores aleatórios.

In [4]:
np.random.randint(10,30, size=(3,5))

array([[20, 14, 27, 21, 21],
       [18, 27, 16, 29, 17],
       [28, 24, 15, 18, 18]])

3. Crie um array com 5 colunas e 10 linhas inicializados com zeros.

In [5]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

4. Crie um array que vá de 0 a 90 pulando de 4 em 4.

In [9]:
np.arange(0,91,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88])

5. Reduza o array (5, 7) a apenas uma dimensão.

In [20]:
a57 = np.random.random((5,7))
a57 = a57.flatten()
a57

array([0.819971  , 0.58393043, 0.14962542, 0.52110395, 0.74589946,
       0.96720491, 0.90950697, 0.94445745, 0.46402521, 0.7741854 ,
       0.95325652, 0.56870934, 0.53340377, 0.53505879, 0.51917481,
       0.82194876, 0.81355647, 0.59865062, 0.64895319, 0.40159683,
       0.07176029, 0.52035982, 0.95989105, 0.73570725, 0.81356072,
       0.18067899, 0.93679439, 0.96362114, 0.19745257, 0.31566824,
       0.15970743, 0.86570468, 0.61902506, 0.26519019, 0.18789344])

6. Considerando que você é um organizador de um jogo de bingo, crie um array que irá representar a cartilha desses jogos de bingo. Os números das suas cartelas variam entre 1 e 30, e você terá 10 participantes. Cada cartela terá 12 números (4, 3). Crie um array que represente esse jogo.

In [23]:
cartela = np.random.randint(1,31,size=(10,4,3))
cartela

array([[[13, 23, 18],
        [19,  4,  2],
        [14, 14,  2],
        [ 2,  9, 22]],

       [[ 8, 29, 27],
        [16,  5,  2],
        [10, 29,  5],
        [ 5, 17,  9]],

       [[ 9, 11,  8],
        [ 6, 28,  7],
        [27, 20,  5],
        [28, 20, 12]],

       [[ 7, 12, 15],
        [ 7, 19, 13],
        [16,  6,  6],
        [27, 20, 21]],

       [[29, 28, 14],
        [21,  4, 12],
        [ 9, 12, 24],
        [17,  2,  3]],

       [[21, 30,  7],
        [23, 11, 21],
        [13, 13, 16],
        [27, 23, 10]],

       [[16,  2,  9],
        [13,  4, 26],
        [ 9, 25, 25],
        [27, 14, 22]],

       [[30, 23, 24],
        [30, 14, 13],
        [21, 22, 10],
        [26, 26,  9]],

       [[27, 27,  2],
        [ 8, 22, 24],
        [23, 27, 25],
        [ 9, 10, 15]],

       [[ 6, 25, 11],
        [12,  3, 28],
        [24, 21, 13],
        [25,  5, 14]]])

7. Faça o reshape das suas cartelas para que haja 5 cartelas de 4 linhas e 6 colunas.


In [24]:
cartela.reshape((5,4,6))

array([[[13, 23, 18, 19,  4,  2],
        [14, 14,  2,  2,  9, 22],
        [ 8, 29, 27, 16,  5,  2],
        [10, 29,  5,  5, 17,  9]],

       [[ 9, 11,  8,  6, 28,  7],
        [27, 20,  5, 28, 20, 12],
        [ 7, 12, 15,  7, 19, 13],
        [16,  6,  6, 27, 20, 21]],

       [[29, 28, 14, 21,  4, 12],
        [ 9, 12, 24, 17,  2,  3],
        [21, 30,  7, 23, 11, 21],
        [13, 13, 16, 27, 23, 10]],

       [[16,  2,  9, 13,  4, 26],
        [ 9, 25, 25, 27, 14, 22],
        [30, 23, 24, 30, 14, 13],
        [21, 22, 10, 26, 26,  9]],

       [[27, 27,  2,  8, 22, 24],
        [23, 27, 25,  9, 10, 15],
        [ 6, 25, 11, 12,  3, 28],
        [24, 21, 13, 25,  5, 14]]])

Manipulando Arrays:

1. Explorando Ecossistemas: 
Como bióloga marinha, me encontrei em uma expedição nas profundezas do Oceano Pacífico, onde estávamos estudando a biodiversidade e a saúde dos recifes de coral. O catálogo abaixo demonstra dados das espécies encontradas, considere a seguinte ordem de colunas:

ID da espécie, quantidade de representantes encontrados, profundeza, tamanho médio da espécie.


In [6]:
especies = np.array([[747, 89, 33, 5], 
                     [623, 123, 32, 13], 
                     [501, 22, 49, 2], 
                     [116, 101, 42, 10], 
                     [297, 56, 69, 22], 
                     [613, 64, 27, 7], 
                     [295, 84, 29, 14], 
                     [692, 105, 72, 16], 
                     [229, 103, 35, 5], 
                     [374, 124, 70, 1]])
especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

- a. Selecione a segunda coluna com a quantidade de representantes encontrados e adicione em um array como qtd_especies.

In [7]:
qtd_especies = especies[:,1]
qtd_especies

array([ 89, 123,  22, 101,  56,  64,  84, 105, 103, 124])

- b. De qtd_especies, selecione apenas as primeiras 3 quantidades e imprima.

In [8]:
print(qtd_especies[0:3])

[ 89 123  22]


- c. Imprima as 5 últimas quantidades de espécies.

In [10]:
print(qtd_especies[-5:])

[ 64  84 105 103 124]


- d. Crie um array que contenha apenas os tamanhos das espécies e ordene por ordem crescente.

In [12]:
np.sort(especies[:,3])

array([ 1,  2,  5,  5,  7, 10, 13, 14, 16, 22])

2. Ainda usando o Array de espécies.

    a. Usando um index boolean, crie um array que contenha os dados da maior espécie encontrada 
    (considerando o seu tamanho). Esse valor corresponde ao valor 22.

    b. Usando fancy index, faça um array que contenha apenas os dados da espécie com ID 297.

    c. Usando np.where(), faça um array com a linha contendo dados 
    correspondentes à espécie com 105 representantes encontrados.

    d. Considere a profundidade em que a espécie foi encontrada e substitua 
    valores maiores que 60 com "Profundo".



Ainda no conjunto 'especies':

a. Adicione mais 2 espécies ao array: [[204, 10, 40, 12], [392, 11, 81, 11]].

b. Adicione mais uma coluna no array original agora com o número de espécies encontradas, indicando se o animal enxerga ou não: [0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0].



Cálculo com Array:

Considerando o array abaixo, responda:

acidentes = np.array([[1, 3, 2], [0, 1, 0], [2, 1, 4], [0, 0, 0], [1, 1, 0]])

1. O cliente que teve acidente abaixo da média nos últimos 2 anos ganhará um desconto no seu seguro. 
Identifique-os.

2. Qual cliente teve pelo menos 2 anos sem cometer acidentes?

3. Uma professora quer que seus alunos apliquem a função (3x + 2y + xy) em um conjunto de dados. 
Ela dá dois arrays aos estudantes e pede que seja feita essa operação.

4. A mesma professora percebeu que houve um erro em todas as provas dos estudantes e 
esqueceu de anotar a nota de trabalhos apresentados durante o semestre. 
Já que foi feito em grupo ela vai adicionar a mesma nota para todos os estudantes. 
No array, cada estudante representa uma linha e cada coluna uma prova. 
Adicione para cada prova de cada estudante os valores: 1, 2, 1.